---
- name: dat ip cho loopback
  hosts: all
  tast:
    - name: Set loopback ipv4 address
      ios_l3_interface:
        name: loopback "{{item.number }}"
        ipv4: 10.0.{{item.ip}}.1/24

      with_item:
        - {number: 1, ip: 1}
        - {number: 2, ip: 2}
        - {number: 3, ip: 3}
